apiVersion: apps/v1
kind: DaemonSet
metadata:      
  name: nginx-ds
  labels:
    env: demo
spec:      
  template:
      metadata:    
        labels:
          env: demo
        name: nginx
      spec:           
        containers:
          - image: nginx
            name: nginx
 # replicas: 3  #this is the number of replicas you want    no need in daemon
  selector:
    matchLabels: 
      env: demo
