apiVersion: apps/v1
kind: ReplicaSet
metadata:      
  name: nginx-deployemnt
  labels:
    env: demo
spec:      
  template:
      metadata:    
        labels:
          env: demo
        name: nginx
      spec:           
        containers:
          - image: nginx
            name: nginx
  replicas: 3 #this is the number of replicas you want
  selector:
    matchLabels: 
      env: demo
